name: Build and Package FBX Python Bindings

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Unzip shared object file
      run: unzip fbx.cpython-312-x86_64-linux-gnu.zip -d .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools

    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: fbxpythonbindings-wheel
        path: dist/*.whl
